### ISSUE TITLE
user tablosu i olusturulacak

### ISSUE THREAD

**Issue by onur-celik** [onur-celik/kartVista#1]
..

**Comment by onur-celik** [comment]
alanlar : 

1 - id
2 - username
3 - name
4 - lastname
5 - about
6 - email
7 - country
8 - city
9 - password
9 - date

**Comment by sinanacar** [comment]
lastip de ekleyelim bence, son giriş yaptığı ip nömerosu.

**Comment by onur-celik** [comment]
napcaz lastip'yi? nerde kullanicaz?

**Comment by sinanacar** [comment]
log tutmamızı isteyecek yetkili makamlar.
